### ISSUE TITLE
bug: media namespace DNS issues

### ISSUE THREAD

**Issue by iT3E** [iT3E/tnwks-ops#111]
Have consistent DNS issues on all systems in the media namespace with setGateway: true.  Pod restart will sometimes fix it temporarily, but not always.  example from Radarr:

```
[v4.6.4.7568] System.Net.Http.HttpRequestException: Name does not resolve (prowlarr.tnwks.local:80)
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name does not resolve
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
```

when testing the indexer, it will either pass immediately, or fail once then pass the second time.  Seems like some sort of forwarder round-robin issue? or something flapping.. unsure so far

**Comment by iT3E** [comment]
still getting DNS errors.  Sometimes the check will state it's a DNS problem, sometimes it will simply time out.

```
  | 10:35pm | RadarrErrorPipeline | Invalid request Validation failed: -- : Unable to connect to indexer, please check your DNS settings and ensure IPv6 is working or disabled. Operation timed out (prowlarr.media.svc.cluster.local:80) |  
  | 10:35pm | Torznab | Unable to connect to indexer: Operation timed out (prowlarr.media.svc.cluster.local:80)

```

when exec into the pod, resolution is working immediately
```
kubectl exec -n media sonarr-778d75844b-wckwr -- nslookup prowlarr.media.svc.cluster.local
Defaulted container "sonarr" out of: sonarr, gateway-sidecar, gateway-init (init)
Server:         172.16.1.1
Address:        172.16.1.1#53

Name:   prowlarr.media.svc.cluster.local
Address: 10.43.171.61
```

starting to look like maybe a prowlarr problem?

**Comment by iT3E** [comment]
definitely something with pod-gateway.  Hubble is showing sonarr/radarr -> prowlarr traffic destined for port 80  going to 'world' rather than to the pod:

```
Flow Details
Timestamp
2023-07-06T05:55:41.484Z
Verdict
forwarded
Traffic direction
egress
Cilium event type
to-stack
TCP flags
SYN
Source pod
radarr-5465cf8f65-hf8z4
Source identity
67217
Source labels
instance=radarr
name=radarr
io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=media
io.cilium.k8s.namespace.labels.kustomize.toolkit.fluxcd.io/name=cluster-apps
io.cilium.k8s.namespace.labels.kustomize.toolkit.fluxcd.io/namespace=flux-system
io.cilium.k8s.namespace.labels.kustomize.toolkit.fluxcd.io/prune=disabled
io.cilium.k8s.namespace.labels.routed-gateway=true
io.cilium.k8s.policy.cluster=home-cluster
io.cilium.k8s.policy.serviceaccount=default
namespace=media
Source IP
10.42.4.143
Destination identity
16777217
Destination labels
cidr:10.0.0.0/8
reserved:world
Destination IP
10.43.171.61
Destination port • protocol
80 • TCP
```

same setup afaik, but qbit connections go directly to the pod and not 'world':
```
Flow Details
Timestamp
2023-07-06T06:00:57.678Z
Verdict
forwarded
Traffic direction
ingress
Cilium event type
to-endpoint
TCP flags
ACKFIN
Source pod
radarr-5465cf8f65-hf8z4
Source identity
67217
Source labels
instance=radarr
name=radarr
io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=media
io.cilium.k8s.namespace.labels.kustomize.toolkit.fluxcd.io/name=cluster-apps
io.cilium.k8s.namespace.labels.kustomize.toolkit.fluxcd.io/namespace=flux-system
io.cilium.k8s.namespace.labels.kustomize.toolkit.fluxcd.io/prune=disabled
io.cilium.k8s.namespace.labels.routed-gateway=true
io.cilium.k8s.policy.cluster=home-cluster
io.cilium.k8s.policy.serviceaccount=default
namespace=media
Source IP
10.42.4.143
Destination pod
qbittorrent-0
Destination identity
116738
Destination labels
instance=qbittorrent
name=qbittorrent
io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=media
io.cilium.k8s.namespace.labels.kustomize.toolkit.fluxcd.io/name=cluster-apps
io.cilium.k8s.namespace.labels.kustomize.toolkit.fluxcd.io/namespace=flux-system
io.cilium.k8s.namespace.labels.kustomize.toolkit.fluxcd.io/prune=disabled
io.cilium.k8s.namespace.labels.routed-gateway=true
io.cilium.k8s.policy.cluster=home-cluster
io.cilium.k8s.policy.serviceaccount=default
namespace=media
statefulset.kubernetes.io/pod-name=qbittorrent-0
Destination IP
10.42.5.249
Destination port • protocol
8080 • TCP
```

**Comment by iT3E** [comment]
Problem is partly here https://github.com/iT3E/tnwks-ops/blob/6da46beead38888408b67797781575edb86a9005/kubernetes/apps/kube-system/cilium/app/helmrelease.yaml#L86

and also with how radarr/sonarr are attempting to access prowlarr, via port 80 rather than what is configured in k8s, port 9696.  When changing port to 9696, packets are routed correctly to the pod rather than to 'world'.
